// <auto-generated />
using System;
using Crane.Infrastructure.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Crane.Infrastructure.EntityFramework.Migrations
{
    [DbContext(typeof(CraneDbContext))]
    partial class CraneDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.InboxState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("Consumed")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid>("ConsumerId")
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("NUMBER(19)");

                    b.Property<Guid>("LockId")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("RAW(16)");

                    b.Property<int>("ReceiveCount")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("Received")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("RAW(8)");

                    b.HasKey("Id");

                    b.HasIndex("Delivered");

                    b.ToTable("InboxState");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.Property<long>("SequenceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SequenceNumber"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)");

                    b.Property<Guid?>("ConversationId")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("DestinationAddress")
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)");

                    b.Property<DateTime?>("EnqueueTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("FaultAddress")
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)");

                    b.Property<string>("Headers")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<Guid?>("InboxConsumerId")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid?>("InboxMessageId")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid?>("InitiatorId")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<Guid?>("OutboxId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Properties")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("ResponseAddress")
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)");

                    b.Property<DateTime>("SentTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("SourceAddress")
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)");

                    b.HasKey("SequenceNumber");

                    b.HasIndex("EnqueueTime");

                    b.HasIndex("ExpirationTime");

                    b.HasIndex("OutboxId", "SequenceNumber")
                        .IsUnique()
                        .HasFilter("\"OutboxId\" IS NOT NULL");

                    b.HasIndex("InboxMessageId", "InboxConsumerId", "SequenceNumber")
                        .IsUnique()
                        .HasFilter("\"InboxMessageId\" IS NOT NULL AND \"InboxConsumerId\" IS NOT NULL");

                    b.ToTable("OutboxMessage");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxState", b =>
                {
                    b.Property<Guid>("OutboxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("NUMBER(19)");

                    b.Property<Guid>("LockId")
                        .HasColumnType("RAW(16)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("RAW(8)");

                    b.HasKey("OutboxId");

                    b.HasIndex("Created");

                    b.ToTable("OutboxState");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.OutboxState", null)
                        .WithMany()
                        .HasForeignKey("OutboxId");

                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.InboxState", null)
                        .WithMany()
                        .HasForeignKey("InboxMessageId", "InboxConsumerId")
                        .HasPrincipalKey("MessageId", "ConsumerId");
                });
#pragma warning restore 612, 618
        }
    }
}
